### ISSUE TITLE
handleError - Chrome bug

### ISSUE THREAD

**Issue by Drotak** [sveltejs/learn.svelte.dev#536]
As you can see in the image below, I'm unable to call the "/the-bad-place" route
![image](https://github.com/sveltejs/learn.svelte.dev/assets/9133109/a4cd0046-1ddf-4e5c-9059-47fdb1ee9f3e)

Chrome Version: 119.0.6045.200 - also tried updating to 120.0.6099.71 - but the problem persists

I also tried this with Firefox 120.0.1 and there it works without a problem

**Comment by dummdidumm** [comment]
Can reproduce this, the console says
```
Error: `line` must be greater than 0 (lines start at line 1)
at originalPositionFor$1 (/home/httpslearnsveltedev-xfsn/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:10168:19)
```
@paoloricciuti didn't you have a similar problem for sveltelab?

**Comment by paoloricciuti** [comment]
> Can reproduce this, the console says
> 
> ```
> Error: `line` must be greater than 0 (lines start at line 1)
> at originalPositionFor$1 (/home/httpslearnsveltedev-xfsn/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:10168:19)
> ```
> 
> @paoloricciuti didn't you have a similar problem for sveltelab?

Yes i had and kinda still have...currently i'm patching sveltekit code on instally to add a try/catch around this https://github.com/sveltejs/kit/blob/5faf68e8eeb75177287f574d02536f30a094ac64/packages/kit/src/exports/vite/dev/index.js#L255-L258C3 to at least avoid that the dev server crashes. I sent a report to the webcontainer team because apparently it only happens in a webcontainer

**Comment by kshyun28** [comment]
Also encountered this issue. 

I'll skip the tutorial page for now.
