### ISSUE TITLE
svelte.dev not running script

### ISSUE THREAD

**Issue by rushirufu** [sveltejs/learn.svelte.dev#623]
### Describe the bug

svelte.dev not running script

I'm lerning https://learn.svelte.dev/tutorial/tweens but all section not running scripts

I'm try to another browser (edge, mozilla, chrome)  but not works

![svelte_gg](https://github.com/sveltejs/svelte/assets/49694049/57268159-8526-4e03-a88e-200ea75d0577)

### Reproduction

svelte.dev not running script

### Logs

```shell
svelte.dev not running script
```

### System Info

```shell
svelte.dev not running script
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is working currently for me.

**Comment by MikeBooon** [comment]
I am also having the same issue on multiple browsers. 
![image](https://github.com/sveltejs/learn.svelte.dev/assets/49905192/5307a4b3-1d10-4cf8-aad8-ca3f3db16467)

**Comment by Selyss** [comment]
I'm having the same issue.

**Comment by 0Ared** [comment]
it works for me.

**Comment by Osato28** [comment]
Same here (macOS 14.5 on M1). 

More detail: 

- on Chrome, the dev server for the tutorial is stuck on "booting webcontainer" seemingly forever (at least, it didn't shift in three minutes). REPL is working fine
- on Firefox, the dev server works for approximately 10-20 seconds but then it stops reading from the code that you're editing. Clicking "Solve" doesn't force the dev container to read from the new version of the code, neither does the "Refresh" button.
- on Safari, it doesn't load at all and requests that the user enables third party cookies for the site (see screenshot). The really weird thing is that it doesn't happen EVERY time; sometimes, it starts up just fine. Also, from the moment that request is shown, the entire system starts lagging until I close the tab.

<img width="1196" alt="Screenshot 2024-06-20 at 21 27 39" src="https://github.com/sveltejs/learn.svelte.dev/assets/65938107/4b070b61-663c-4377-8e99-298d957cb48e">

Additionally, the request shown on the screenshot offers the user to switch to a legacy version of the tutorial, which is no longer present under [that URL](https://svelte.dev/tutorial/welcome-to-svelte). The legacy URL might be useful in tracing the bug, so here it is in plaintext:

https://svelte.dev/tutorial/welcome-to-svelte

**Comment by Osato28** [comment]
Addendum: I self-hosted this repo on my computer to see if I can replicate the issue locally.

Attempts to replicate the issue succeeded with a 300% efficiency. Now in _all_ browsers, it has the same issue: stuck on "booting webcontainer". The issue is present whether you run it with dev or with build.

Browser console shows nothing aside from CORS and connectivity errors (to be expected, since I'm still IP-banned from svelte.dev).

If the command used to run the server is "dev", no errors are displayed. If the command used to run the server is "preview", the following error is shown in the command line with every page refresh:

```
TypeError: immutable
    at _Headers.set (node:internal/deps/undici/undici:8616:17)
    at Object.handle (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/chunks/hooks.server.js:3:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/index.js:2563:22)
    at async fetch (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/index.js:2320:26)
SvelteKitError: Not found: /_vercel/speed-insights/script.js
    at resolve2 (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/index.js:2732:18)
    at resolve (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/index.js:2565:34)
    at Object.handle (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/chunks/hooks.server.js:2:26)
    at respond (file:///Users/anonymized/Documents/GitHub/learn.svelte.dev/.svelte-kit/output/server/index.js:2563:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
```

but that seems to be linked to a failed fetch of vercel's speed tracker ("at async fetch" in the middle), which is to be expected for a self-host on a local machine.

---

System parameters:
macOS 14.5 on M1
node v22.3.0
package managers used to build and host: pnpm 9.4.0 and yarn 1.22.19, each used separately on different copies of the repo.
